name: Vzduch-Dotek
version: 1.0.0
slug: vzduch-dotek
description: Airtouch3 api
startup: application
boot: auto
arch:
  - aarch64
  - armhf
  - armv8
url: 'https://github.com/pjfian/home-assistant-addons'
image: 'ghcr.io/pjfian/airtouch3:latest'
webui: 'http://[HOST]:[PORT:5353]/api/aircons'
ports:
  5353/tcp: 5353
ports_description:
  5353/tcp: 'Airtouch3 web api'
init: false
options:
  airtouch_ip: '192.168.86.35'
  airtouch_port: 8899
  logLevel: 'Information'
schema:
  airtouch_ip: str
  airtouch_port: int
  logLevel: str